### ISSUE TITLE
Feature Request - Play Custom Sounds From Texture Pack

### ISSUE THREAD

**Issue by Nozemi** [mrgeneralq/sleep-most#102]
## Feature Explanation
Currently there are config values for sounds. Right now that only supports the Sound enum found in the server. Although the enum is just a more convenient way to programmatically play sounds. When using configuration files, it's better to just use the string-based key itself.

Snippet of Sound.java ([API Docs - Sound Enum](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html))
```java
public enum Sound implements Keyed {
    AMBIENT_BASALT_DELTAS_ADDITIONS("ambient.basalt_deltas.additions"),
    AMBIENT_BASALT_DELTAS_LOOP("ambient.basalt_deltas.loop"),
    AMBIENT_BASALT_DELTAS_MOOD("ambient.basalt_deltas.mood"),
    AMBIENT_CAVE("ambient.cave"),
    ...
}
```

With the values of the enum being what they are, you can have the default config value be:
```yaml
# Add sound effects after skipping the night or storm
sounds:
  night-skipped:
    enabled: false
    sound: ui.toast.challenge_complete
  storm-skipped:
    enabled: false
    sound: entity.wither.spawn
```
<details>
<summary><b>Old config for reference:</b></summary>
```yaml
# Add sound effects after skipping the night or storm
sounds:
  night-skipped:
    enabled: false
    sound: UI_TOAST_CHALLENGE_COMPLETE
  storm-skipped:
    enabled: false
    sound: ENTITY_WITHER_SPAWN
```
</details>

<hr />

Doing it this way should be easier for server owners to understand as well, as they don't necessarily understand why it has to be `ENTITY_WITHER_SPAWN`, which only makes sense if you're a developer and know enums.

Resources players could use then are naturally also tied to their Minecraft client version, but there are resources like:
- [Sounds List - digminecraft.com/...](https://www.digminecraft.com/lists/sound_list_pc.php)
- [Sounds List - cimapinecraft.com/...](https://cimapminecraft.com/tutorials/minecraft-playsound-list#minecraft-playsound-list)

They can then just use the command to play sound ([command docs](https://www.digminecraft.com/game_commands/playsound_command.php)):
```
/playsound <sound> <source> <targets> [x] [y] [z] [volume] [pitch] [minimumVolume]
``` 
With the command they first test the sound they want works, then they can update the config value with that after.

<hr />

### Sound Method Being Used
Currently using `playSound()`-method that takes Sound enum as paramter. However, there is another method, which is the exact same that takes a `String`-value which can be used instead.

See:
- (_current_) [playSound(Sound)][sound-method-enum]
- (_new_) [playSound(String)][sound-method-string]

### Change Methods Getting Sound Effect
Currently [ConfigService#getSoundNightSkippedSound()][get-night-skipped-sound] and [ConfigService#getSoundStormSkippedSound()][get-storm-skipped-sound] uses a try catch to parse the configured value into the enum.

- Try/Catch here is not ideal, as you might want to throw the exception if this is wrongfully configured. Because when someone configures this and leaves the value incorrect, they expect it to work in game, but it won't, and there won't be any errors.
- We don't need to use the Sound enum at all anymore, so this can just return a String instead.

[get-night-skipped-sound]: https://github.com/mrgeneralq/sleep-most/blob/457eeec788490719c37059adead5391a678d5d11/src/main/java/me/mrgeneralq/sleepmost/services/ConfigService.java#L71
[get-storm-skipped-sound]: https://github.com/mrgeneralq/sleep-most/blob/457eeec788490719c37059adead5391a678d5d11/src/main/java/me/mrgeneralq/sleepmost/services/ConfigService.java#L89

[sound-method-enum]: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,org.bukkit.Sound,org.bukkit.SoundCategory,float,float)
[sound-method-string]: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,java.lang.String,float,float)
