### ISSUE TITLE
afk detection using placeholderapi output

### ISSUE THREAD

**Issue by cupang-afk** [mrgeneralq/sleep-most#188]
**Is your feature request related to a problem? Please describe.**
i dont use essentials but i use [AFKPlus](https://github.com/LapisPlugins/AFKPlus) to record afk player

**Describe the solution you'd like**
AFKPlus has extension named [AFKPlusPAPI](https://github.com/Dart2112/AFKPlusPAPI) that enable placeholderapi for afk player

in the [AFKPlusPAPI config](https://github.com/Dart2112/AFKPlusPAPI/blob/master/src/main/resources/config.yml) i can set placeholder output for afk player and non afk player

i want to use this output for sleep-most plugin to detect the afk player like

```yaml
set-afk-placeholder: %AFKPlus_Status%
placeholder-is-afk: "True"
placeholder-is-not-afk: "False"
```
