### ISSUE TITLE
French messages translation

### ISSUE THREAD

**Issue by criticalsool** [mrgeneralq/sleep-most#191]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding french translation to the plugin

**Comment**
Hello, as a thank you for your excellent plugin, here's a french translation of the messages.yml file. I have not seen any language support yet, but if you ever need the french one, it will be there.

```yml
# CUSTOMIZE MESSAGES FOR SLEEP-MOST.
# To disable messages set the message to ''
# Placeholders are available here --> https://sleepmost.pseudonova.com/placeholders/sleepmost-config
# You need support? Join our Discord server --> https://discord.pseudonova.com/
#
# Add multiple messages to randomly select by doing the following:
# messagetype:
#  - 'message1'

prefix: ''
user:
  night-skipped-chat: '&aBonjour, %player% !'
  storm-skipped-chat: '&aLe ciel se dégage !'
  players-left-night: '&bJoueurs requis pour passer la nuit : &c%sleeping%/%required% &b!'
  players-left-storm: '&bJoueurs requis pour passer l''orage : &c%sleeping%/%required% &b!'
  sleep-prevented: '&cVous ne pouvez pas dormir dans ce monde !'
  no-sleep-storm: '&cVous ne pouvez pas dormir pendant un orage !'
  cannot-sleep-now: '&cVous ne pouvez pas dormir pour le moment'
  sleep-success: '&4Vous vous endormez profondément...'
  no-longer-sleeping: '&cVous ne dormez plus'
  no-bed-location-set: '&cIl n''y a pas de lit disponible'
  teleported-to-bed: '&bVous avez été téléporté à votre lit'
  sleep-command-disabled: '&cLa commande pour dormir est désactivée'
  insomnia-not-sleepy: '&cVous souffrez d''&4insomnie'
  insomnia-feeling-sleepy: '&bVous commencez enfin à somnoler...'
  kicked-player-from-bed: '&bVous avez éjecté &a%player% &bde son lit'
  kicked-from-bed: '&cVous avez été éjecté de votre lit'
  kicking-not-allowed: '&cVous n''avez pas la permission d''éjecter ce joueur de son lit'
  night-skipped-title: '&aNuit passée'
  night-skipped-subtitle: '&bBonjour %player% !'
  storm-skipped-title: '&eOrage passé'
  storm-skipped-subtitle: '&bQuel temps...'
  longer-night:
    sleep-prevented: '&cLa nuit est plus longue que d''habitude, vous ne vous sentez pas encore fatigué'
boss-bar:
  title: '&bJoueurs présents dans leur lit : &c%sleeping-count%&f/&c%sleeping-required-count%'
admin:
  no-console-command: '&cCette commande ne peut pas être executé depuis la console'
  no-permission-command: '&cVous n''avez pas la permission de faire ça'
  unknown-command: '&cCommande inconnue'
  config-reloaded: '&aVous avez rechargé avec succès le plugin Sleep-Most'
  already-enabled-for-world: '&cSleep-Most est déjà activé dans &a%world%'
  already-disabled-for-world: '&cSleep-Most est déjà désactivé dans &a%world%'
  enabled-for-world: '&bSleep-Most est maintenant activé dans &a%world%'
  disabled-for-world: '&cSleep-Most est maintenant désactivé dans &a%world%'
  not-enabled-for-world: '&cSleep-Most n''est pas activé dans &a%world%&c. Activez le avec &a/sm enable'
  currently-disabled: '&bSleepmost est actuellement &cdésactivé &bpour ce monde. Entrez
    &a/sm enable &bpour activer sleepmost dans ce monde'
  one-player-sleep-set: '&bLe mode un joueur nécessaire est paramétré'
  specify-player: '&cSpécifiez avec le nom du joueur'
  target-not-sleeping: '&cLe joueur n''est pas entrain de dormir'
  target-not-online: '&cLe joueur n''est pas en ligne'
  insomnia-already-enabled: '&cInsomnie est déjà activé dans ce monde'
  insomnia-enabled: '&bInsomnie est activé'
  only-during-night-command: '&cCette commande peut uniquement être utilisé la nuit'
  kick-out-bed: '&c&l[éjecté]'
flag:
  all-reset-success: '&cTous les flags ont été réinitialisé'
  set-in-world: '&La valeur du flag &e%flag% &bdans ce monde est &e%value%&b.'
  reset-in-world: '&bLe flag &e%flag% &bà été réinitialisé à &e%default-value%'
  not-exist: '&cCe flag n''existe pas'
clock:
  title: '&6%time%'
  subtitle: '&a> > >'
```
