### ISSUE TITLE
Option to sync sleep between worlds.

### ISSUE THREAD

**Issue by barrettford** [mrgeneralq/sleep-most#54]
It would be helpful if I could specify in the config that I want to keep the world's time in-sync.
`sync-worlds: true` or something similar.

Or, to be more configurable, I'd have an entry under each world with the names of the other worlds sleep-most should time-skip whenever it is triggered for this world.
```
world:
  also-set: 
    - world2
    - world3

world2:
  also-set: 
    - world
    - world3

world3:
  also-set: 
    - world
    - world2
```
like this.
